openapi: 3.1.0
info:
  title: Plex API
  version: '1.0'
  summary: API endpoints used by the Plex web player.
  description: ''
servers:
  - url: 'http://192.168.50.203:32400'
paths:
  /servers:
    get:
      summary: List Servers
      tags: []
      operationId: get-servers
      parameters:
        - $ref: '#/components/parameters/Accept'
      description: Retrieve a list of servers available to the authenticated user.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  MediaContainer:
                    type: object
                    required:
                      - size
                      - Server
                    properties:
                      size:
                        type: integer
                      Server:
                        type: array
                        items:
                          $ref: '#/components/schemas/Server'
                required:
                  - MediaContainer
            application/xml:
              schema:
                type: object
                properties:
                  MediaContainer:
                    type: object
                    required:
                      - size
                      - Server
                    properties:
                      size:
                        type: integer
                      Server:
                        type: array
                        items:
                          $ref: '#/components/schemas/Server'
                required:
                  - MediaContainer
              examples:
                Example:
                  value: |-
                    <MediaContainer size="1">
                        <Server name="PlexServer-PC" host="127.0.0.1" address="127.0.0.1" port="32400" machineIdentifier="6d55bd9816sgb319a05e1a37aa607gf21cv1cb9c" version="1.24.1.4931-1a38e63c6"/>
                    </MediaContainer>
    parameters: []
components:
  schemas:
    Server:
      description: ''
      type: object
      x-examples:
        example-1:
          name: HTPC-Ubuntu
          host: 192.168.50.203
          address: 192.168.50.203
          port: 32400
          machineIdentifier: 6d95bd98160bb619a05e1a375a6076f21cf1c49d
          version: 1.24.1.4931-1a38e63c6
      properties:
        name:
          type: string
        host:
          type: string
        address:
          type: string
        port:
          type: integer
        machineIdentifier:
          type: string
        version:
          type: string
      required:
        - name
        - host
        - address
        - port
        - machineIdentifier
        - version
      examples:
        - name: PlexServer-PC
          host: 127.0.0.1
          address: 127.0.0.1
          port: 0
          machineIdentifier: string
          version: string
  securitySchemes:
    API Key - 1:
      name: X-Plex-Token
      type: apiKey
      in: query
  parameters:
    Accept:
      name: Accept
      in: header
      required: false
      schema:
        enum:
          - application/xml
          - application/json
        type: string
        default: application/xml
security:
  - API Key - 1: []
